### PR TITLE
Fix redirect URL in github plugin and extending documentation

### PR DESCRIPTION
**Pull request by cawka**

### CODE REVIEW

**Comment by OctoGerrit** [comment]
I've not had an issue with OAuth for Github.  I know for Google, the www.url.com/oauth callback is required, but for Github, I just use http://www.url.com/#/ for the callback without issue.  When I use the GH OAuth vs Google OAuth, it creates a new account for the GH and links to the existing Google.  I did see your post on the Issue 2766 about allowing OAuth to connect multiple providers to a single account.

**Comment by cawka** [comment]
I was trying that, but no authentication was happening.  I mean, I was going to github page, authorizing, and then getting redirected to just main page of my gerrit, with option to sign in again.

When I tried to specify something different for github application, I was getting error from github:  gerrit was showing me "Not found" page and from URI i saw that it is about mismatch of redirect URLs.

**Comment by OctoGerrit** [comment]
Ah ha, I see what your saying.  There is a: callback = "url" setting for the plugin, have you tried setting that?  Certainly if it defaults to url/oauth, then hopefully David will pull and merge, but it might give you more options that way as well.

**Comment by cawka** [comment]
Yes, before modifying source, I was trying to set callback parameter for the provider.  However, it didn't want to take my settings and I assumed that the URL is hard-coded...

**Comment by davido** [comment]
Thanks for the fix and documentation. May be put the documetation into the GitHub Wiki as well, in new page: Getting Started => Configuration?

**Comment by cawka** [comment]
Sure. The easier access to documentation, the simpler would be life for users :)

**Comment by davido** [comment]
Done. ;-)

 https://github.com/davido/gerrit-oauth-provider/wiki/Getting-Started

**Pull request merged**
