### PR TITLE
Pr/add gitlab oauth

### PR DESCRIPTION
**Pull request by netroby**
We using Gitlab account to login gerrit in our company

### CODE REVIEW

**Comment by davido** [comment]
Thanks for your contribution. Overall looks good to me. I would also prefer not to spread this feature to so many commits. Also note, that every single commit must compile.

Please also update README.md file and add GitLab to the list of supported OAuth providers.

**Comment by dreef3** [comment]
Do you think this could be reopened and merged? I really much like to use this

**Comment by davido** [comment]
Sure, I reviewed the PR, but my comments weren't addressed.

**Comment by netroby** [comment]
Sorry. This feature is just for our company usage . so i open source these code, but not quite good quality for public usage. it just dirty and work. just for our mission.

**Pull request closed without merging**
