### PR TITLE
Added Bitbucket OAuth plugin.

### PR DESCRIPTION
**Pull request by Opalo**
Added Bitbucket OAuth plugin. New classes are formatted with [this](https://github.com/gerrit-review/gerrit/blob/master/tools/GoogleFormat.xml) configuration file. Existing classes modified only with the code required.

### CODE REVIEW

**Comment by Opalo** [comment]
@davido, corrected all the issues you pointed out.

**Comment by davido** [comment]
Thanks. Can you squash all commits in one single commit? I prefer to merge one single commit and not series of commits. If all other options fail, please create new PR with one single commit.

**Comment by Opalo** [comment]
All commits squashed. You want me to update the README.md file before merge as well?

**Comment by davido** [comment]
> All commits squashed. You want me to update the README.md file before merge as well?

Sure, one single commit.

**Comment by Opalo** [comment]
@davido `README.md` updated.

**Comment by Opalo** [comment]
@davido, `README.md` corrected with appropriate OAuth providers order.

**Comment by davido** [comment]
Thank you for contribution and for addressing all comments.

**Comment by Opalo** [comment]
You're welcome. Thank you very much!

**Pull request merged**
