### PR TITLE
Bitbucket OAuth added.

### PR DESCRIPTION
**Pull request by Opalo**
I've implemented Bitbucket OAuth. Please review and let me know if it can be merged in.

### CODE REVIEW

**Comment by davido** [comment]
LGTM. Unfortunately, you changed quite some styles, importing etc. Please check Eclipse setting file from Gerrit project: [1] and reformat the patch. In general content changes should never be done in combination with formatting changes. You also missing license header in new files.

[1] https://github.com/gerrit-review/gerrit/blob/master/Documentation/dev-contributing.txt#L147-L179

**Comment by Opalo** [comment]
Thanks for feedback @davido. Will fix it as soon as possible. Nasty formatting - I always forget about it, but you're absolutely right!

**Comment by Opalo** [comment]
@davido I've added license statements and corrected formatting (used eclipse and this [file](https://github.com/gerrit-review/gerrit/blob/master/tools/GoogleFormat.xml) to format the code). Please let me know if everything works fine.

**Comment by davido** [comment]
Thanks, But I would prefer not to apply the reformatting, as it may differ from the original files. Can't you create new merge request, where only new code is changed, and the old code is untouched?

**Comment by Opalo** [comment]
Sure @davido. I'll prepare new merge patch on tomorrow and issue a pull request - this one can be closed then :)

**Comment by davido** [comment]
Thanks.

**Pull request closed without merging**
